name: windows-msys2

on: [push, pull_request]

defaults:
  run:
    shell: msys2 {0}

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      with: 
        submodules: 'true'

    - uses: msys2/setup-msys2@v2
      with:
          install: >-
            mingw-w64-x86_64-nasm
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-make
            mingw-w64-x86_64-gcc

    - name: cmake
      working-directory: src
      run: cmake -B build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
    
    - name: build
      working-directory: src\build
      run: cmake --build . --config ${{env.BUILD_TYPE}}
    
    - uses: actions/upload-artifact@v1
      with:
        name: ect-win-x86-64
        path: src\build\ect.exe
